# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XCAInventoryTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCAInventoryTracker

end

target 'XCAInventoryTrackerVision' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCAInventoryTrackerVision

end
